NetCoreIdentity/Controllers/PanelController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NetCoreIdentity.Context;
using NetCoreIdentity.Models;
using System;
using System.IO;
using System.Threading.Tasks;

namespace NetCoreIdentity.Controllers
{
    [Authorize]
    [AutoValidateAntiforgeryToken]
    public class PanelController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;
        public PanelController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager)
        {
            _userManager = userManager;
            _signInManager = signInManager;
        }
        public async Task<IActionResult> Index()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            return View(user);
        }
        public async Task<IActionResult> UpdateUser()
        {
            var user = await _userManager.FindByNameAsync(User.Identity.Name);
            UserUpdateViewModel model = new UserUpdateViewModel
            {
                Name = user.Name,
                SurName = user.SurName,
                PhoneNumber = user.PhoneNumber,
                Email = user.Email,
                PictureUrl = user.PictureUrl
            };
            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateUser(UserUpdateViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userManager.FindByNameAsync(User.Identity.Name);
                if (model.Picture != null)
                {
                    string dirPath = Directory.GetCurrentDirectory();
                    string pictureName = Guid.NewGuid() + Path.GetExtension(model.Picture.FileName);
                    string path = dirPath + "/wwwroot/img/" + pictureName;
                    using FileStream stream = new FileStream(path, FileMode.Create);
                    await model.Picture.CopyToAsync(stream);
                    user.PictureUrl = pictureName;
                }
                user.Name = model.Name;
                user.SurName = model.SurName;
                user.Email = model.Email;
                user.PhoneNumber = model.PhoneNumber;
                var result = await _userManager.UpdateAsync(user);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                foreach (var item in result.Errors)
                {
                    ModelState.AddModelError("", item.Description);
                }
            }
            return View(model);
        }

        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

NetCoreIdentity/Views/Panel/Index.cshtml
@model AppUser
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-8">
            <table class="table table-hover table-sm">
                <tr>
                    <th>İsim:</th>
                    <td>@Model.Name</td>
                </tr>
                <tr>
                    <th>Soyisim:</th>
                    <td>@Model.SurName</td>
                </tr>
                <tr>
                    <th>Email:</th>
                    <td>@Model.Email</td>
                </tr>
                <tr>
                    <th>Telefon:</th>
                    <td>@Model.PhoneNumber</td>
                </tr>
            </table>
        </div>
        <div class="col-md-4">
            <img src="~/img/@Model.PictureUrl" alt="@Model.Name" class="w-100 img-fluid img-thumbnail" />
        </div>
    </div>
</div>

NetCoreIdentity/Views/Panel/UpdateUser.cshtml
@model UserUpdateViewModel
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3 class="modal-header">Bilgilerimi Güncelle</h3>

<div class="container-fluid">
    <div class="row">
        <form asp-action="UpdateUser" asp-controller="Panel" method="post" enctype="multipart/form-data" class="w-75 mx-auto p-3 bg-light">
            <div class="form-group">
                <div class="col-md-4">
                    <label>Profil Resminiz</label>
                    <img src="~/img/@Model.PictureUrl" alt="@Model.Name" class="card-img" />
                </div>
                <div class="col-md-8">
                    <input type="file" asp-for="Picture" class="form-control-file" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <span asp-validation-for="Name" class="text-danger"></span>
                <input asp-for="Name" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="SurName"></label>
                <span asp-validation-for="SurName" class="text-danger"></span>
                <input asp-for="SurName" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="Email"></label>
                <span asp-validation-for="Email" class="text-danger"></span>
                <input asp-for="Email" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber"></label>
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                <input asp-for="PhoneNumber" class="form-control" />
            </div>
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <button class="btn btn-info">Kaydet</button>
        </form>
    </div>
</div>